services:
  mvault-nginx:
    image: nginx:alpine
    container_name: mvault-nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - mvault-app
    networks:
      - mvault-network
  #Database Service
  mvault-db:
    image: mariadb
    container_name: mvault-db
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    ports:
      - "3334:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${SQL_ROOT}
      MARIADB_DATABASE: safe
      MARIADB_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - mvault-network
  # Application Service
  mvault-app:
    container_name: mvault-app
    build:
      context: .
      dockerfile: ./php.Dockerfile
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor
      - ./session:/var/php/sessions/
    env_file: .env
    ports:
      - "9000:80"
    networks:
      - mvault-network
  #mvault-phpmyadmin Service
  mvault-phpmyadmin:
    image: phpmyadmin:latest
    container_name: mvault-phpmyadmin
    ports:
      - "8086:80"
    environment:
      UPLOAD_LIMIT: 300M
    depends_on:
      - mvault-db
    networks:
      - mvault-network
networks:
  mvault-network:
    driver: bridge
